config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
  	root 'notes#index', as: "authenticated_root"
  end

 
  root 'welcome#index'

  
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit,:update, :destroy]

	def index
		@notes = Note.where(user_id: current_user)
	end

	def show
	end

	def new	
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)

		if @note.save
			redirect_to @note
		else
			render 'new'
		end		

	end

	def edit
		
	end

	def update
		if @note.update(note_params)
			redirect_to @note
		else
		render 'edit'			
		end
	end

	def destroy
		@note.destroy
		redirect_to notes_path
	end

	private

	def find_note
		@note = Note.find(params[:id])
	end

	def note_params
		params.require(:note).permit(:title, :content)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/app.haml
!!! 5
%html(lang="en")
%head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %title dotNote
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    %meta{:content => "initial-scale=1, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no", :media => "(device-height: 568px)", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %link{:href => "/assets/touch-icon-iphone.png", :rel => "apple-touch-icon-precomposed", :type => "image/png"}/
    %link{:href => "/assets/touch-icon-ipad.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72", :type => "image/png"}/
    %link{:href => "/assets/touch-icon-iphone-retina.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114", :type => "image/png"}/
    %link{:href => "/assets/touch-icon-ipad-retina.png", :rel => "apple-touch-icon-precomposed", :sizes => "152x144", :type => "image/png"}/
    %link{:rel=> "stylesheet", :href=> "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}
    = csrf_meta_tags
%body
    %nav.navbar.navbar-inverse{:role => "navigation"}
        .container-fluid
            .navbar-header
                %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                    %span.sr-only Toggle navigation
                    %span.icon-bar
                    %span.icon-bar
                    %span.icon-bar
                %a.navbar-brand{:href => root_path} .Note
            #bs-example-navbar-collapse-1.collapse.navbar-collapse
                - if user_signed_in?
                    %ul.nav.navbar-nav.navbar-right
                        %li
                            %a{:href => new_note_path} New Note
                        %li
                            %a{:href => edit_user_registration_path} Account
                        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
                            
                - else
                    %ul.nav.navbar-nav.navbar-right
                        %li
                            %a{:href => new_user_session_path} Log In
                        %li
                            %a{:href => new_user_registration_path} Sign Up     
            
            .container   
            
        - if notice
            %div.notification_wrapper_notice
                %p.notice= notice     
        - elsif alert
            %div.notification_wrapper_alert
                %p.alert= alert         


    =yield     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  
  <title>dotNote</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1.0"/>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1.0, minimum-scale=1.0" media="(device-height: 568px)"/>
  <meta name="apple-mobile-web-app-capable" content="yes"/>

  <meta name="description" content="You online NoteBook. Never forget an idea again">
  <meta name="keywords" content="education, platform, smart phone, tablet, mobile, social, inclusive, HTML5, classroom, engagement, play, game, fun, quiz, multi-player, pedagogy, learning model, learn, gamification, notebook, notes, online." />
  
  <link rel="shortcut icon" href="assets/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="/assets/touch-icon-iphone.png"/>
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/touch-icon-ipad.png"/>
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/touch-icon-iphone-retina.png"/>
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/touch-icon-ipad-retina.png"/>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"/>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
  
  <link rel="stylesheet" type="text/css" href="/assets/addtohomescreen.css">
  <script src="/assets/addtohomescreen.js"></script>
  <script>
  addToHomescreen({
      detectHomescreen: true
  });
  </script>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">.Note</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="<%= new_note_path %>">New Note</a>
            </li>
            <li>
              <a href="<%= edit_user_registration_path %>">Account</a>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="<%= new_user_session_path %>">Log In</a>
            </li>
            <li>
              <a href="<%= new_user_registration_path %>">Sign Up     </a>
            </li>
          </ul>
        <% end %>
      </div>
      <div class="container"></div>
    </div>
    <% if notice %>
      <div class="notification_wrapper_notice">
        <p class="notice">
    <%= notice %>
        </p>
      </div>
    <% elsif alert %>
      <div class="notification_wrapper_alert">
        <p class="alert">
    <%= alert %>
        </p>
      </div>
    <% end %>
  </nav>
  <%= yield %>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63340732-1', 'auto');
  ga('send', 'pageview');
  </script>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
%head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %title dotNote
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    %meta{:content => "initial-scale=1, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no", :media => "(device-height: 568px)", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %link{:href => "/assets/touch-icon-iphone.png", :rel => "apple-touch-icon-precomposed", :type => "image/png"}/
    %link{:href => "/assets/touch-icon-ipad.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72", :type => "image/png"}/
    %link{:href => "/assets/touch-icon-iphone-retina.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114", :type => "image/png"}/
    %link{:href => "/assets/touch-icon-ipad-retina.png", :rel => "apple-touch-icon-precomposed", :sizes => "152x144", :type => "image/png"}/
    %link{:rel=> "stylesheet", :href=> "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}
    = csrf_meta_tags
%body
    %nav.navbar.navbar-inverse{:role => "navigation"}
        .container-fluid
            .navbar-header
                %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                    %span.sr-only Toggle navigation
                    %span.icon-bar
                    %span.icon-bar
                    %span.icon-bar
                %a.navbar-brand{:href => root_path} .Note
            #bs-example-navbar-collapse-1.collapse.navbar-collapse
                - if user_signed_in?
                    %ul.nav.navbar-nav.navbar-right
                        %li
                            %a{:href => new_note_path} New Note
                        %li
                            %a{:href => edit_user_registration_path} Account
                        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
                            
                - else
                    %ul.nav.navbar-nav.navbar-right
                        %li
                            %a{:href => new_user_session_path} Log In
                        %li
                            %a{:href => new_user_registration_path} Sign Up     
            
            .container   
            
        - if notice
            %div.notification_wrapper_notice
                %p.notice= notice     
        - elsif alert
            %div.notification_wrapper_alert
                %p.alert= alert         


    =yield     

app/views/notes/_form.html.haml
.form-group
    = simple_form_for @note, html: { multipart: true } do |f|
        = f.input :title
        = f.input :content

        = f.button :submit, class: "btn btn-success"

app/views/notes/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
    .row
        .panel.panel-default-custom
            .panel-heading
                %h1 Edit Your Note
            .panel-body
                = render 'form' 
                %button.btn.btn-danger
                    =link_to "Cancel", note_path
        

app/views/notes/index.html.haml
%body.show-body
    .container
        .wrapper_with_padding
            #notes.clearfix
                %a{ href: new_note_path }
                    .note_new
                        %i.fa.fa-plus-circle     
                        %p.title= "Add a New Note"
                     
                #notes.clearfix
                    - @notes.each do |note|       
                        %a{ href: (url_for [note])}
                            .note
                                %p.title= note.title
                                %p.date= time_ago_in_words(note.created_at)
                                                               
                            

app/views/notes/new.html.haml
.panel.panel-default-custom
    .panel-heading
        %h1 Add a New Note
    .pannel-body   
        = render 'form'
        %button.btn.btn-danger
            =link_to "Cancel", root_path 

app/views/notes/show.html.haml
%body
    .container
        .wrapper_with_padding
            #note_show
                %h1.title= @note.title
                %p.date=@note.created_at.strftime("%d %b, %Y")
                %a.credits{:href => edit_user_registration_path(@note)}= @note.user.name
                %a.btn.btn-warning.btnshow{:href => edit_note_path(@note)} Edit
                %a.btn.btn-danger.btnshow{:href => note_path(@note), :method => :delete, data: {confirm: "Are You Sure?"}} Delete
                %p= simple_format (@note.content)
                
                    
                  

app/views/welcome/index.html.haml
.banner-red.banner-exact
    .container
        .row
            .col-md-12
        .row
            .col-md-12
                .banner-btns.center-block
                    %h1.text-center dotNote
        .row
            .col-md-8.col-md-offset-2
                %p.climb.text-center Your online NoteBook. Never forgget an idea again
        .row
            .banner-btns-log
                %a.action-btn.animate.center-block.yellow{:href => new_user_registration_path} Sign Up
                %a.action-btn.animate.center-block.blue{:href => new_user_session_path} Log In    
.ban-mid
    .container
        .row.same-height-parent
            .col-md-12
                .panel.same-height{:style => "height: 308px;"}
                    .panel-heading
                        %h1.panel-title One Workspace, Many Ideas
                        %i.fa.fa-file-text-o
#callouts
    .callout_inner
        .wrapper
            .callout
                %i.fa.fa-pencil
                %h2 Notes
                %p The easiest way to make your notes look attractive. Make your classroom a better place to read NoteBooks.
            .callout
                %i.fa.fa-rocket
                %h2 Rocket
                %p The easiest way to make your notes look attractive. Make your classroom a better place to read NoteBooks.
            .callout
                %i.fa.fa-lightbulb-o
                %h2 Light
                %p The easiest way to make your notes look attractive. Make your classroom a better place to read NoteBooks.  

#bottom_cta
    .wrapper
        %h2 Share your Ideas!      
        %p Its <strong>Free</strong> and always will be<strong>...</strong>
        %a.action-btn.animate.center-block.yellow{:href => new_user_registration_path} Sign Up

.footer
    .container-fluid
        .row.footer-imprint
            %p &copy; 2015 dotNot